# -*- coding: utf-8 -*-
"""CC2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AMM5W8M_k0p7BN_AGuzYHD1ADRRNPAwW

Question 1
"""

rollNumber=1024160011
L=[]
while rollNumber>0:
    f=rollNumber%10
    L.append(f*10)
    rollNumber=rollNumber//10
print(L)

L.append(12)
print(L)
#Number 12 is added at the end of the list

L.insert(4,12)
#12 is added at index 4

print(L)

x=L.pop(4)
print(L)
print(x)
#It gives the number popped also and removes number by index

L.remove(0)
print(L)
#Removes first occurence of the number in list

L.sort()
print(L)

L.sort(reverse=True)
print(L)

print(L[:3])

print(L[7:])

avg = sum(L) / len(L)
print("The list L is ",L)
print("Its average is ",avg)

NewL = [x for x in L if x>avg]

print("Number greater than avg are ",NewL)

"""Question 2"""

scores=tuple(L[i] for i in range(0,8) )
print(scores)

highest=max(scores)
highest_index=scores.index(highest)
print(highest_index)

lowest = min(scores)
lowest_count = scores.count(lowest)
print(lowest_count)

# Tuples are immutable, so they cannot be reversed in place like lists.
reversed_tuple=list(reversed(scores))
print(reversed_tuple)

score=int(input("What is the number "))
if score in scores:
  print(scores.index(score))
else:
  print("Not in the tuple")

scores[0]=100
#Tupples are immutable

first, second, *remaining = scores

print("First:", first)
print("Second:", second)
print("Remaining:", remaining)

"""Question 3"""

import random

random.seed(1024160011)

numbers = [random.randint(100, 900) for i in range(100)]
print(numbers)

count=0
for i in range(0,100):
  if numbers[i]%2!=0:
    print(numbers[i])
    count+=1
print("Number of odd numbers are ",count)

count=0
for i in range(0,100):
  if numbers[i]%2==0:
    print(numbers[i])
    count+=1
print("Number of even numbers are ",count)

def is_prime(n):
    if n < 2:
        return False

    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False

    return True
primeNums=[]
for i in range (1,100):
  if is_prime(numbers[i]):
    primeNums.append(numbers[i])
print(primeNums)
print(len(primeNums))

most_frequent = max(set(numbers), key=numbers.count)
print("Most frequent is ",most_frequent," and is count is ",numbers.count(most_frequent))

"""Question 4"""

roll_no = "1024160011"

digits = [int(d) for d in str(roll_no)]


A = {digit * 7 for digit in digits}
B = {digit * 9 for digit in digits}

print("Set A:", A)
print("Set B:", B)


union = A.union(B)
print("Union:", union)


intersection = A.intersection(B)
print("Intersection:", intersection)

A_minus_B = A.difference(B)
B_minus_A = B.difference(A)

print("A - B:", A_minus_B)
print("B - A:", B_minus_A)

# difference() gives values present in one set but not the other
# for the specified direction, while symmetric_difference()
# gives values that are present in either set but not both.

symmetric_diff = A.symmetric_difference(B)
print("Symmetric Difference:", symmetric_diff)


print("Is A a subset of B?", A.issubset(B))
print("Is B a superset of A?", B.issuperset(A))


X = int(input("Enter a value to remove from A: "))

A.discard(X)

print("Set A after discard:", A)

# discard() is safer than remove() because it does not
# give an error if the value is not present in the set.

"""Ques 5"""

my_dict = {
    "name": "Arnav Singh",
    "roll_no": "YOUR_ROLL_NUMBER",
    "branch": "YOUR_BRANCH",
    "age": 20,
    "city": "YOUR_CITY"
}

print("Original Dictionary:")
print(my_dict)



my_dict["location"] = my_dict.pop("city")

print("\nAfter renaming city to location:")
print(my_dict)



my_dict["cgpa"] = 8.25

print("\nAfter adding CGPA:")
print(my_dict)


#
my_dict["age"] = my_dict["age"] + 1

print("\nAfter increasing age by 1:")
print(my_dict)


dict_pop = my_dict.copy()

removed_branch = dict_pop.pop("branch")

print("\nUsing pop():")
print(dict_pop)
print("Removed value:", removed_branch)


dict_del = my_dict.copy()

del dict_del["branch"]

print("\nUsing del:")
print(dict_del)

# pop() removes the key and returns its value,
# whereas del only removes the key-value pair.



print("\nKey-Value pairs:")

for key, value in my_dict.items():
    print(key, "→", value)


if "email" in my_dict:
    print("\nEmail:", my_dict["email"])
else:
    print("\nEmail key does not exist.")


friend_dict = {
    "name": "Rahul",
    "roll_no": "12345678",
    "branch": "CSE",
    "age": 20,
    "city": "Delhi"
}

merged_dict = {**my_dict, **friend_dict}

print("\nMerged Dictionary:")
print(merged_dict)

# When both dictionaries have the same key,
# the value from friend_dict wins because it comes second.


string_values = {
    key: value
    for key, value in my_dict.items()
    if isinstance(value, str)
}

print("\nDictionary containing only string values:")
print(string_values)